server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/erpsystemdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
mybatis:
  type-aliases-package: cn.bdqn.erpsystem.pojo
  mapper-locations: classpath*:mapper/*.xml
