server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/erpsystemdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
#    日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML
#    encoding: utf-8
#    cache: false
mybatis:
  type-aliases-package: cn.bdqn.erpsystem.pojo
  mapper-locations: classpath*:mapper/*.xml
